name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # ==============================
  #         CONTINUOUS INTEGRATION
  # ==============================
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          python manage.py collectstatic --noinput
          python manage.py test

      # === Docker build testing ===
      - name: Build Docker Image
        run: |
          docker build -t farhod/chatapp:latest .

  # ==============================
  #        CONTINUOUS DEPLOYMENT
  # ==============================
  cd:
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & Push Docker image
      - name: Build & Push image
        run: |
          docker build -t farhod2007/chatapp:${{ github.sha }} .
          docker push farhod2007/chatapp:${{ github.sha }}


      # ==== SSH DEPLOY ====

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "===== SERVER INFO ====="
            hostname
            hostname -I
            whoami
            pwd
            echo "======================="

            cd /home/Doppigram

            export IMAGE_TAG=${{ github.sha }}

            docker pull farhod2007/chatapp:${IMAGE_TAG}
            docker compose down
            docker compose up -d

            docker compose run --rm web python manage.py migrate
            docker compose run --rm web python manage.py collectstatic --noinput

#      - name: Deploy to Production Server
#        uses: appleboy/ssh-action@v1.1.0
#        with:
#          host: ${{ secrets.SERVER_IP }}
#          username: ${{ secrets.SERVER_USER }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          script: |
#            cd /home/Doppigram
#
#            export IMAGE_TAG=${{ github.sha }}
#
#            docker compose down
#            docker compose pull
#            docker compose up -d --force-recreate
#
#            docker compose exec web python manage.py migrate
#            docker compose exec web python manage.py collectstatic --noinput
