name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # CONTINUOUS INTEGRATION
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          python manage.py collectstatic --noinput
          python manage.py test

      # Docker build testing
      - name: Build Docker Image
        run: |
          docker build -t farhod/chatapp:latest .

  # CONTINUOUS DEPLOYMENT
  cd:
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # üîç DEBUG STEP (ENG MUHIM JOY)
      - name: "DEBUG: show build context"
        run: |
          echo "PWD:"
          pwd
          echo "LS ROOT:"
          ls -la
          echo "CHECK manage.py:"
          ls -la manage.py || echo "manage.py YO‚ÄòQ"
          echo "CHECK config/:"
          ls -la config || echo "config/ YO‚ÄòQ"
          echo "SHOW urls.py:"
          sed -n '1,200p' config/urls.py || echo "urls.py YO‚ÄòQ"

      # Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & Push Docker image
      - name: Build & Push image
        run: |
          docker build -t farhod2007/chatapp:latest .
          docker push farhod2007/chatapp:latest

      # ==== SSH DEPLOY ====
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/Doppigram
          
            docker compose down
            docker compose pull
            docker compose up -d --force-recreate
          
            docker compose exec web python manage.py migrate
            docker compose exec web python manage.py collectstatic --noinput
